version: '3.3'
services:

  redis:
    image: redis:latest

  flask:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app/:/app/
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    command: |
      python run.py